name: CI
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - uses: actions/setup-node@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - run: sbt compile serverProd/docker:publishLocal