name: CI
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: sbt "scalafmtSbtCheck; scalafmtCheckAll; test:compile; clientDev/fastOptJS::webpack; clientProd/fullOptJS::webpack"
      # Only Linux container setup is provided and GitHub Actions do not support Linux containers on Windows
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sbt serverProd/docker:publishLocal